const jobs = [
  {
    id: 1,
    type: "Full Time",
    role: "Senior React Developer",
    desc: "Lead the development of complex front end interfaces using React, hooks, and modern state management tools.",
    pay: "$70,000 to $80,000 per year",
    loc: "Boston, MA",
  },
  {
    id: 2,
    type: "Part Time",
    role: "Junior Front End Developer",
    desc: "Assist the engineering team with UI components, bug fixes, and layout adjustments for ongoing projects.",
    pay: "$25 to $30 per hour",
    loc: "Remote",
  },
  {
    id: 3,
    type: "Contract",
    role: "Node.js Backend Engineer",
    desc: "Work on API development, database design, and integration for a high traffic web platform.",
    pay: "$45 to $60 per hour",
    loc: "Austin, TX",
  },
  {
    id: 4,
    type: "Full Time",
    role: "UI UX Designer",
    desc: "Create user centered designs, wireframes, and prototypes that support new product features.",
    pay: "$65,000 to $75,000 per year",
    loc: "New York, NY",
  },
  {
    id: 5,
    type: "Internship",
    role: "Frontend Intern",
    desc: "Support senior developers with testing, component styling, and documentation.",
    pay: "$15 to $18 per hour",
    loc: "Chicago, IL",
  },
  {
    id: 6,
    type: "Remote",
    role: "React Native Developer",
    desc: "Develop mobile interfaces for iOS and Android apps using React Native and modern libraries.",
    pay: "$80,000 to $95,000 per year",
    loc: "Remote",
  },
  {
    id: 7,
    type: "Full Time",
    role: "Product Manager",
    desc: "Drive product strategy, gather requirements, and collaborate with cross functional teams.",
    pay: "$90,000 to $110,000 per year",
    loc: "San Francisco, CA",
  },
  {
    id: 8,
    type: "Full Time",
    role: "DevOps Engineer",
    desc: "Manage CI CD pipelines, cloud infrastructure, and system reliability.",
    pay: "$100,000 to $120,000 per year",
    loc: "Atlanta, GA",
  },
  {
    id: 9,
    type: "Contract",
    role: "PHP Laravel Developer",
    desc: "Build and maintain backend services for company platforms using Laravel and MySQL.",
    pay: "$40 to $55 per hour",
    loc: "Miami, FL",
  },
  {
    id: 10,
    type: "Full Time",
    role: "Full Stack JavaScript Developer",
    desc: "Work across frontend and backend services with React and Node.js.",
    pay: "$85,000 to $100,000 per year",
    loc: "Seattle, WA",
  },
  {
    id: 11,
    type: "Remote",
    role: "Technical Writer",
    desc: "Create documentation, guides, and API references for engineering teams.",
    pay: "$50,000 to $65,000 per year",
    loc: "Remote",
  },
  {
    id: 12,
    type: "Full Time",
    role: "Cybersecurity Analyst",
    desc: "Monitor systems for threats and maintain strong security practices.",
    pay: "$75,000 to $90,000 per year",
    loc: "Houston, TX",
  },
  {
    id: 13,
    type: "Part Time",
    role: "IT Support Technician",
    desc: "Provide technical support, handle troubleshooting, and maintain systems.",
    pay: "$22 to $30 per hour",
    loc: "Los Angeles, CA",
  },
  {
    id: 14,
    type: "Contract",
    role: "Data Analyst",
    desc: "Analyze datasets and help stakeholders make data driven decisions.",
    pay: "$35 to $50 per hour",
    loc: "Denver, CO",
  },
  {
    id: 15,
    type: "Full Time",
    role: "Cloud Architect",
    desc: "Design scalable cloud solutions for enterprise applications.",
    pay: "$120,000 to $150,000 per year",
    loc: "Phoenix, AZ",
  },
  {
    id: 16,
    type: "Remote",
    role: "QA Automation Engineer",
    desc: "Build automated test suites for web applications and APIs.",
    pay: "$75,000 to $95,000 per year",
    loc: "Remote",
  },
  {
    id: 17,
    type: "Full Time",
    role: "Marketing Manager",
    desc: "Develop campaigns and manage marketing strategies for product growth.",
    pay: "$70,000 to $85,000 per year",
    loc: "Dallas, TX",
  },
  {
    id: 18,
    type: "Full Time",
    role: "Android Developer",
    desc: "Create native Android apps and maintain existing products.",
    pay: "$80,000 to $100,000 per year",
    loc: "San Diego, CA",
  },
  {
    id: 19,
    type: "Remote",
    role: "Content Strategist",
    desc: "Plan and optimize content for digital channels and brand messaging.",
    pay: "$45,000 to $60,000 per year",
    loc: "Remote",
  },
  {
    id: 20,
    type: "Contract",
    role: "Machine Learning Engineer",
    desc: "Build predictive models and deploy machine learning pipelines.",
    pay: "$60 to $85 per hour",
    loc: "Boston, MA",
  },
];


export  {jobs}